/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 earth.gltf --transform
Files: earth.gltf [60.91MB] > earth-transformed.glb [1.81MB] (97%)
Author: AirStudios (https://sketchfab.com/sebbe613)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/earth-5f9c35be31a047928eace8b415a8ee3a
Title: Earth
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/earth-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.pSphere1_phong1_0.geometry} material={materials.phong1} scale={56.724} />
      <mesh geometry={nodes.pSphere4_lambert6_0.geometry} material={materials.lambert6} scale={57.464} />
      <mesh geometry={nodes.pSphere5_lambert7_0.geometry} material={materials.lambert7} scale={58.098} />
    </group>
  )
}

useGLTF.preload('/earth-transformed.glb')
