/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 low_poly_ruby.gltf --transform
Files: low_poly_ruby.gltf [3.74KB] > low_poly_ruby-transformed.glb [1.94KB] (48%)
Author: endrit (https://sketchfab.com/endrit)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/low-poly-ruby-786187083f994954a1db1ed9392c12b8
Title: Low Poly Ruby
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/low_poly_ruby-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cylinder_0.geometry} material={materials.Material} position={[0.325, 1.436, 0]} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/low_poly_ruby-transformed.glb')
