/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 python_programming_language.gltf --transform
Files: python_programming_language.gltf [10.4KB] > python_programming_language-transformed.glb [5.04KB] (52%)
Author: Acvantad (https://sketchfab.com/Acvantad)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/python-programming-language-44d992bf56e244448e9ee5b4da083287
Title: Python Programming language
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/python_programming_language-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_4.geometry} material={materials.material} position={[-0.002, 0, 0]} rotation={[Math.PI / 2, 0, 0]} scale={2.501} />
      <mesh geometry={nodes.Object_6.geometry} material={materials['.001']} position={[-0.002, 0, 0]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={2.501} />
    </group>
  )
}

useGLTF.preload('/python_programming_language-transformed.glb')
